version: "3"
services:
  exdiary:
    image: tnvmadhav/exercisediary
    restart: unless-stopped
    ports:
    - 8851:8851
    volumes:
    - ~/.dockerdata/ExerciseDiary:/data/ExerciseDiary
    environment:
      TZ: Asia/Novosibirsk    # required, default: ""
      HOST: "127.0.0.1"        # optional, default: 0.0.0.0
      PORT: "8851"            # optional, default: 8851
      THEME: "grass"          # optional, default: grass
      COLOR: "light"          # optional, default: light